Models/SecondPageModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment1.Models
{
    public class SecondPageModel
    {
        [Range(0,100, ErrorMessage ="The Number must be between 0 and 100")]
        public double Assignments { get; set; }
        [Range(0, 100, ErrorMessage = "The Number must be between 0 and 100")]
        public double Projects { get; set; }
        [Range(0, 100, ErrorMessage = "The Number must be between 0 and 100")]
        public double Quiz { get; set; }
        [Range(0, 100, ErrorMessage = "The Number must be between 0 and 100")]
        public double exam { get; set; }
        [Range(0, 100, ErrorMessage = "The Number must be between 0 and 100")]
        public double INTEX { get; set; }

    }
}

Controllers/FirstController.cs
using Assignment1.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment1.Controllers
{
    public class FirstController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("SecondPage")]
        public IActionResult SecondPage()
        {
            return View();
        }


        [HttpPost("SecondPage")]
        public IActionResult SecondPage(SecondPageModel model)
        {
            return View();
        }
    }
}

Views/First/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "Matt's Assignment #2";
    ViewBag.MyName = "Matt Mecham";
    ViewBag.Page = "Home Page";
}


<!DOCTYPE html>


<body>
    <h1>@ViewBag.Page</h1>
    <img src="~/img/IMG_20201022_085742871.jpg" />
    <p>I hope to learn how to better build websites and use technology to my advantage. I also hope to learn other useful skills to the programming world</p>
    <br />
    <h2>Top 3 Jobs (Kind of, I'm not really sure)</h2>
    <ul class="Quiz">
        <li>1. Cybersecurity</li>
        <li>2. Project Manager</li>
        <li>3. Data Analyst</li>
    </ul>

</body>

Views/First/SecondPage.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Page = "SecondPage";
}

@model Assignment1.Models.SecondPageModel


<body>
    <h1>@ViewBag.Page</h1>
    <h2>This is my Second Page</h2>
    <h2>Grade Calculator</h2>
    <form method="Post">
        <label>Assignments</label>
        <input id="Assignments" type="number" asp-for="Assignments" />
        <br />
        <label>Group Projects</label>
        <input id="Projects" type="number" asp-for="Projects" />
        <br />
        <label>Quizes</label>
        <input id="Quiz" type="number" asp-for="Quiz" />
        <br />
        <label>Exams</label>
        <input id="exam" type="number" asp-for="exam" />
        <br />
        <label>INTEX</label>
        <input type="number" id="INTEX" asp-for="INTEX" />
        <br />
        <br />
        <input type="submit" id="submitButton" />
        <div asp-validation-summary="All"></div>
    </form>

</body>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link rel="icon" type="image/jpg" href="~/img/download2.png" />
    <link href="~/css/main.css" rel="stylesheet" />
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <header>
        <h1>@ViewBag.Test</h1>
        <menu>
            <ul>
                <li><a asp-controller="First" asp-action="Index">Home</a></li>
                <li><a asp-controller="First" asp-action="SecondPage">Second Page</a></li>
            </ul>
        </menu>
    </header>
    @RenderBody()
    <footer>Test Test</footer>
    <script src="~/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="~/js/fanmail.js"></script>
</body>

</html>